name: Manual Database Build
on:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      SEGA_ID: ${{ secrets.SEGA_ID }}
      SEGA_PASSWORD: ${{ secrets.SEGA_PASSWORD }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install dependencies
        run: yarn
      - name: Build record database
        run: yarn generate:records
      - name: Build stamp card
        run: yarn generate:stamp
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
  build:
    runs-on: ubuntu-latest
    needs: generate
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PUBLIC_URL: https://shiftpsh.com/
      GENERATE_SOURCEMAP: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist
          bucket: ${{ vars.S3_BUCKET_PRODUCTION }}
          bucket-region: ${{ vars.S3_BUCKET_REGION }}
          dist-id: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID_PRODUCTION }}
          no-cache: true
          private: true
